basic_settings:
  site_title: Patrick McDavid
  site_tagline: Technology leadership from Colorado - thoughts on SaaS, games, and the human side of engineering
  favicon_image: /images/favicon.png

header_settings:
  logo_image: 
  logo_width: 200
  overlay_opacity: 0.7

menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
    - title: 'All Posts'
      url: '/archive/'
    - title: 'Projects'
      url: '/projects/'
    - title: 'Résumé'
      url: '/files/PatrickMcDavidResume2025.pdf'
    - title: 'About'
      url: '/about'

grid_settings:
  grid_spacing: 10

contact_settings:
  form_action: 'https://formspree.io/your@email.com'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: 'https://www.facebook.com/patrick.mcdavid'
  twitter_url: 'https://www.twitter.com/ehippy'
  instagram_url: 'https://www.instagram.com/ehippy/'
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: 'https://github.com/ehippy/'
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: 'https://www.linkedin.com/in/pmcdavid/'
  rss_url: 'http://patrickmcdavid.com/feed.xml'

color_settings:
  background_color: '#ffffff'
  background_alt_color: '#F5F7FA'
  text_dark_color: '#2A2F36'
  text_medium_color: '#6C7A89'
  text_light_color: '#ABB7B7'
  text_zazz_color: '#0f9d57'
  accent_color: '#0f9d57'
  border_color: '#dddddd'
  overlay_background_color: '#161B21'
  overlay_text_color: '#ffffff'
  error_color: '#D64541'

  # Dark mode colors
  dark_background_color: '#1a1a1a'
  dark_background_alt_color: '#2d2d2d'
  dark_text_dark_color: '#ffffff'
  dark_text_medium_color: '#b0b0b0'
  dark_text_light_color: '#808080'
  dark_border_color: '#404040'
  dark_overlay_background_color: '#0d0d0d'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Merriweather:300,400,800|Muli:400,400i,600,800" rel="stylesheet">'
  title_font: '"Merriweather", sans-serif'
  body_font: '"Muli", sans-serif'
  regular_weight: 400
  bold_weight: 800
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 400
    letter_spacing: 0
  site_tagline:
    small_size: 16
    medium_size: 17
    large_size: 18
    weight: 400
    letter_spacing: 0
    line_height: 1.5
  menu:
    small_size: 30
    medium_size: 17
    large_size: 18
    weight: 400
    letter_spacing: 0
  h1:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 400
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 20
    medium_size: 28
    large_size: 30
    weight: 400
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 18
    medium_size: 22
    large_size: 26
    weight: 400
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 15
    medium_size: 18
    large_size: 22
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 16
    medium_size: 18
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 15
    medium_size: 20
    large_size: 25
    weight: 400
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""

# Dark mode settings
theme_settings:
  enable_dark_mode: true
  default_theme: "auto" # "light" or "dark" or "auto" (follows system preference)
  show_theme_toggle: true